# Generated by Django 5.1.4 on 2024-12-25 16:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("train_station", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="trip",
            options={"ordering": ("departure_time",)},
        ),
        migrations.AddField(
            model_name="trip",
            name="crew",
            field=models.ManyToManyField(related_name="trips", to="train_station.crew"),
        ),
        migrations.AlterField(
            model_name="train",
            name="cargo_num",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AlterField(
            model_name="train",
            name="places_in_cargo",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
    ]
