# Generated by Django 5.1.4 on 2024-12-29 09:04

import train_station.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "train_station",
            "0002_alter_trip_options_trip_crew_alter_train_cargo_num_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="crew",
            options={"verbose_name": "Crew", "verbose_name_plural": "Crews"},
        ),
        migrations.AlterModelOptions(
            name="order",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Order",
                "verbose_name_plural": "Orders",
            },
        ),
        migrations.AlterModelOptions(
            name="route",
            options={"verbose_name": "Route", "verbose_name_plural": "Routes"},
        ),
        migrations.AlterModelOptions(
            name="station",
            options={"verbose_name": "Station", "verbose_name_plural": "Stations"},
        ),
        migrations.AlterModelOptions(
            name="ticket",
            options={
                "ordering": ("cargo", "seat"),
                "verbose_name": "Ticket",
                "verbose_name_plural": "Tickets",
            },
        ),
        migrations.AlterModelOptions(
            name="train",
            options={"verbose_name": "Train", "verbose_name_plural": "Trains"},
        ),
        migrations.AlterModelOptions(
            name="traintype",
            options={
                "verbose_name": "Train Type",
                "verbose_name_plural": "Train Types",
            },
        ),
        migrations.AlterModelOptions(
            name="trip",
            options={
                "ordering": ("departure_time",),
                "verbose_name": "Trip",
                "verbose_name_plural": "Trips",
            },
        ),
        migrations.AlterField(
            model_name="station",
            name="latitude",
            field=models.FloatField(
                validators=[train_station.models.validate_latitude]
            ),
        ),
        migrations.AlterField(
            model_name="station",
            name="longitude",
            field=models.FloatField(
                validators=[train_station.models.validate_longitude]
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="cargo",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="seat",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name="train",
            unique_together={("name", "train_type")},
        ),
        migrations.AddIndex(
            model_name="route",
            index=models.Index(
                fields=["source", "destination"], name="train_stati_source__23d340_idx"
            ),
        ),
    ]
